spring:
  datasource:
    base-dome:
      dome1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dome1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 12369
      dome2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dome2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 12369

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 10
        min-idle: 2
        max-wait: 100
        max-active: 11
    password: 12369
    timeout: 10000

auth:
  jwt:
    keyLocation: cert/jwt.jks
    keyAlias: jwt
    keyPassword: 123456
    jwtIss: ${spring.application.name}
    expireSeconds: 60
    autoRefreshToken: true

logging:
  level:
    pers.xiaomuma: debug
