spring:
  datasource:
    base-dome:
      dome1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.198.25.4:3306/yd_logistic?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: yxbl12369
      dome2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.198.25.4:3306/tianqi_airport?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: yxbl12369

logging:
  level:
    pers.xiaomuma: debug
